//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pto_restful_service.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class entities : DbContext
    {
        public entities()
            : base("name=entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<answer> answers { get; set; }
        public virtual DbSet<personality> personalities { get; set; }
        public virtual DbSet<personality_test> personality_test { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<test_result> test_result { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_answer> user_answer { get; set; }
    }
}
