//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pto_restful_service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public int id { get; set; }
        public string question_content { get; set; }
        public int test_id { get; set; }
    }
}
